### ISSUE TITLE
Can't output into subdirectory

### ISSUE THREAD

**Issue by emertechie** [bengsfort/rollup-plugin-generate-html-template#21]
My config:

```js
export default {
  input: 'src/main.ts',
  output: {
    dir: 'public',
    entryFileNames: '[name].[hash].js',
    chunkFileNames: '[name].[hash].js',
    format: 'iife',
  },
  plugins: [
    htmlTemplate({
      template: 'src/index.html',
      target: 'public/index.html', // << Note: root of output dir
      replaceVars,
    }),
    htmlTemplate({
      template: 'src/views/modal.html',

      // This always gets output in root of /public dir
      target: 'public/views/modal.html', // << Note: subdir in output dir

      replaceVars,
    }),
  ],
};
```

In my source I have index.html in the root folder and then a `views/` folder for other views. I'd like that mirrored in the output folder but it doesn't seem possible as views always get output in root of output dir. Any suggestions or is it a bug? Thanks

**Comment by dmitrybirin** [comment]
👋 Got the same issue ☝️ 
As I see from the source code `target` parameter is using only for the name creating.
Got one workaround in the plugin, will try to create a PR from it:)
