### ISSUE TITLE
Missing dist in npm packages rollup-plugin-generate-html-template@1.1.1

### ISSUE THREAD

**Issue by baetheus** [bengsfort/rollup-plugin-generate-html-template#3]
Build is missing in release version 1.1.1

**Comment by matheusalbino** [comment]
+Info: Is true, the dist folder is missing

Error: Cannot find module 'rollup-plugin-generate-html-template'

![image](https://user-images.githubusercontent.com/6087948/53086620-34879780-34e4-11e9-950f-8db6be7cf9a6.png)

**Comment by saxoncameron** [comment]
+1

For anyone else coming across this you can simply roll back to 1.1.0 in the meantime.

**Comment by baetheus** [comment]
#4 Resolves this issue

**Comment by yinxin630** [comment]
+1

**Comment by Sara2009** [comment]
+1 
Error: Cannot find module 'rollup-plugin-generate-html-template

**Comment by bengsfort** [comment]
This is fixed and published in `v1.1.3` thanks to @baetheus (#4).

Really sorry about this, as stated in #4 my development time is currently spent off of github and I no longer work on web stuff so I unfortunately haven't been using rollup lately, so I missed all of these notifications completely.
