### ISSUE TITLE
Doesn't work when the target directory doesn't exist

### ISSUE THREAD

**Issue by sarneeh** [bengsfort/rollup-plugin-generate-html-template#5]
Consider this simple config:
```js
{
  input: 'src/index.js',
  output: {
    file: 'dist/index.js',
    format: 'cjs'
  },
  plugins: [
    html({
      template: 'src/index.html',
      target: 'index.html'
    })
  ]
}
```

Now, if the directory `dist` doesn't exist, the plugin errors with `(html-template plugin) Error: ENOENT: no such file or directory, open 'dist/index.html'`

I'd rather expect this plugin to ensure that the directory it tries to write to exist. What do you think about this?

**Comment by bengsfort** [comment]
Fixed with `v1.2.0`.
